#:schema node_modules/wrangler/config-schema.json
name = "gateway-dns-report"
main = "src/index.js"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true

[vars]
 API_TOKEN = "xx-RPBh8kINav4rW"
 ZONE_TAG  = "xx"


# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 7 * * *"] 

[[send_email]]
name = "SEND_EMAIL"
